INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (1, 'San Francisco', 'CA', 'US');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (2, 'Chennai', 'TA', 'India');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (3, 'Madurai', 'TA', 'India');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (4, 'Bengalore', 'KA', 'India');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (5, 'Theni', 'TN', 'India');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (6, 'Toronto', 'ON', 'Canada');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (7, 'Montreal', 'QB', 'Canada');
INSERT INTO CITY (ID, NAME, STATE, COUNTRY) VALUES (8, 'Quebec', 'QB', 'Canada');